USE AMAZON

CREATE TABLE EMPLOYEE(EMPID INT IDENTITY(100,5), EMPNAME CHAR(20), EMPSALARY MONEY, EMPLOC CHAR(10))

SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES ('JOHN',1200,'HYD')
INSERT INTO EMPLOYEE VALUES ('PETER',1300,'CHENNAI')
INSERT INTO EMPLOYEE VALUES ('HARRY',1400,'PUNE')
INSERT INTO EMPLOYEE VALUES ('SMITH',1800,'BNG')
INSERT INTO EMPLOYEE VALUES ('MICHEAL',1900,'DELHI')


CREATE TABLE NETFLIX(NET_MOV_ID INT, NET_MOV_NAME CHAR(20), NET_MOV_BUG MONEY)

CREATE TABLE PRIME (PRI_MOV_ID INT,PRI_MOV_NAME CHAR(20),PRI_MOV_BUG MONEY)

SELECT * FROM NETFLIX
SELECT * FROM PRIME

INSERT INTO NETFLIX VALUES (1,'PB',100)
INSERT INTO NETFLIX VALUES (2,'VIKING',200)
INSERT INTO NETFLIX VALUES (3,'GOT',300)
INSERT INTO NETFLIX VALUES (4,'MONEYHEIST',400)
INSERT INTO NETFLIX VALUES (5,'SKYWALK',500)

INSERT INTO PRIME VALUES (10,'SSRED',1000)
INSERT INTO PRIME VALUES (11,'ANACONDA',2000)
INSERT INTO PRIME VALUES (2,'VIKING',200)
INSERT INTO PRIME VALUES (13,'SNAKES',3000)
INSERT INTO PRIME VALUES (14,'CONJURING',4000)
INSERT INTO PRIME VALUES (4,'MONEYHEIST',400)

UNION:

SELECT* FROM NETFLIX
UNION
SELECT* FROM PRIME

UNIONALL:

SELECT* FROM NETFLIX
UNION ALL
SELECT* FROM PRIME

INTERSECTION:

SELECT *FROM NETFLIX
INTERSECT
SELECT *FROM PRIME

EXCEPT:

SELECT *FROM NETFLIX 
EXCEPT 
SELECT *FROM PRIME 