/* CREATE THE TABLE */

USE AMAZON

CREATE TABLE EMPLOYEE_DETAILS(EMPID INT,EMPNAME CHAR,EMPSALARY MONEY)

/* ALTER */
ALTER TABLE EMPLOYEE_DETAILS ALTER COLUMN EMPNAME VARCHAR

ALTER TABLE EMPLOYEE_DETAILS ADD EMPLOC CHAR
USE AMAZON
ALTER TABLE EMPLOYEE_DETAILS DROP COLUMN EMPNAME

/* SP_RENAME */
SP_RENAME 'EMPLOYEE_DETAILS.EMPSALARY','INCOME'

/* VIEW THE TABLE*/
SELECT * FROM EMPLOYEE_DETAILS
SELECT EMPID,EMPLOC FROM EMPLOYEE_DETAILS

/* INSERT */
ALTER TABLE EMPLOYEE_DETAILS ALTER COLUMN EMPLOC CHAR(10)
INSERT INTO EMPLOYEE_DETAILS VALUES(1,1200,'HYD')
INSERT INTO EMPLOYEE_DETAILS VALUES(2,1400,'CHENNAI')
INSERT INTO EMPLOYEE_DETAILS VALUES(3,1600,'BANGLORE')
INSERT INTO EMPLOYEE_DETAILS VALUES(4,1800,'NOIDA')
INSERT INTO EMPLOYEE_DETAILS VALUES(5,2000,'PUNE')

/* UPDATE */
UPDATE EMPLOYEE_DETAILS SET INCOME=2600 WHERE EMPID=3

/* DELETE */
DELETE EMPLOYEE_DETAILS WHERE EMPID=5
DELETE EMPLOYEE_DETAILS

/*TRUNCATE*/
TRUNCATE TABLE EMPLOYEE_DETAILS

/*DROP*/
DROP TABLE EMPLOYEE_DETAILS