CREATE DATABASE FACEBOOK

USE FACEBOOK

CREATE TABLE EMPLOYEE (ID TINYINT,EMPNAME VARCHAR(10),EMPSALARY MONEY)

CREATE TABLE STUDENT (ID TINYINT,STDNAME VARCHAR(20),STDLOC CHAR(10))

INSERT INTO EMPLOYEE VALUES (1,'KIRAN',100)
INSERT INTO EMPLOYEE VALUES (2,'KUMAR',150)
INSERT INTO EMPLOYEE VALUES (3,'SAI',180)
INSERT INTO EMPLOYEE VALUES (4,'PRAVEEN',200)
INSERT INTO EMPLOYEE VALUES (5,'GOUTHAM',250)
INSERT INTO EMPLOYEE VALUES (6,'ANAND',350)
INSERT INTO EMPLOYEE VALUES (7,'ARAVIND',400)

INSERT INTO STUDENT VALUES (11,'JOHN','UK')
INSERT INTO STUDENT VALUES (12,'PETER','UK')
INSERT INTO STUDENT VALUES (1,'HARRY','USA')
INSERT INTO STUDENT VALUES (13,'SMITH','INDIA')
INSERT INTO STUDENT VALUES (2,'MICHEAL','JAPAN')
INSERT INTO STUDENT VALUES (14,'SURYA','CHINA')
INSERT INTO STUDENT VALUES (3,'KARTHIK','RUSSIA')

SELECT *FROM STUDENT
SELECT *FROM EMPLOYEE
/* ANSI JOINS */
INNER_JOIN:

SELECT* FROM EMPLOYEE INNER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

LEFT_OUTER_JOIN:

SELECT* FROM EMPLOYEE LEFT OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

RIGHT_OUTER_JOIN:

SELECT *FROM EMPLOYEE RIGHT OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

FULL_OUTER_JOIN:

SELECT *FROM EMPLOYEE FULL OUTER JOIN STUDENT ON EMPLOYEE.ID=STUDENT.ID

CROSS_JOIN:

SELECT *FROM STUDENT CROSS JOIN EMPLOYEE

/*NON ANSI JOINS*/

EQUI_JOIN:

SELECT *FROM EMPLOYEE,STUDENT WHERE EMPLOYEE.ID = STUDENT.ID

NON_EQUI_JOIN:

SELECT *FROM EMPLOYEE,STUDENT WHERE STUDENT.ID > EMPLOYEE.ID
