CREATE TABLE EMPLOYEE(EMPID INT, EMPNAME CHAR(20), EMPSALARY MONEY)

INSERT:

INSERT INTO EMPLOYEE VALUES (1,'JOHN',1200)
INSERT INTO EMPLOYEE VALUES (2,'PETER',1400)
INSERT INTO EMPLOYEE VALUES (3,'HARRY',1800)
INSERT INTO EMPLOYEE VALUES (4,'SMITH',2400)
INSERT INTO EMPLOYEE VALUES (5,'MICHEAL',2800)
INSERT INTO EMPLOYEE VALUES (6,'CENA',3000)
INSERT INTO EMPLOYEE VALUES (7,'VIRAT')


PROJECTION_METHOD:

SELECT *FROM EMPLOYEE

SELECTION_METHOD:

SELECT EMPID,EMPNAME FROM EMPLOYEE
