CREATE DATABASE NETFLIX 

USE NETFLIX

CREATE TABLE EMPLOYEE (EMPID INT,EMPNAME CHAR(10),EMPAGE TINYINT)

SELECT *FROM EMPLOYEE

/* INSERTING USING ONLY SQL-SAVED IN RAM*/
INSERT INTO EMPLOYEE VALUES (1,'JOHN',27)

BEGIN TRANSACTION 
ROLLBACK

/*INSTERTING DATA USING TCL ALONG WITH SQL-SAVED IN TEMPORARY MEMORY(BUFFER MEMORY)*/
BEGIN TRANSACTION
INSERT INTO EMPLOYEE VALUES (1,'JOHN',27)
INSERT INTO EMPLOYEE VALUES (2,'PETER',30)
INSERT INTO EMPLOYEE VALUES (3,'STEVE',50)
INSERT INTO EMPLOYEE VALUES (4,'PREM',55)
INSERT INTO EMPLOYEE VALUES (5,'KUMAR',22)

BEGIN TRANSACTION
UPDATE EMPLOYEE SET EMPAGE=80 WHERE EMPAGE=30
COMMIT

BEGIN TRANSACTION 
UPDATE EMPLOYEE SET EMPNAME='LAILA' WHERE EMPID=3
COMMIT

BEGIN TRANSACTION 
UPDATE EMPLOYEE SET EMPID=40 WHERE EMPID=4
COMMIT

BEGIN TRANSACTION 
UPDATE EMPLOYEE SET EMPID=50 WHERE EMPID=5

BEGIN TRANSACTION 
UPDATE EMPLOYEE SET EMPID=10 WHERE EMPID=1

BEGIN TRANSACTION 
UPDATE EMPLOYEE SET EMPAGE=20 WHERE EMPAGE=80

BEGIN TRANSACTION 
ROLLBACK 

TRUNCATE TABLE EMPLOYEE

/* SAVE POINT */

BEGIN TRANSACTION 
DELETE EMPLOYEE WHERE EMPID=1
DELETE EMPLOYEE WHERE EMPID=3
SAVE TRANSACTION R1;
DELETE EMPLOYEE WHERE EMPID=5

BEGIN TRANSACTION 
ROLLBACK TRANSACTION R1


SELECT *FROM EMPLOYEE