/* CREATING THE TABLE */
CREATE TABLE EMPLOYEE (EMPID INT,EMPNAME VARCHAR(10),EMPSALARY MONEY)

/* INSERT THE DATA TO THE EMPLOYEE TABLE  */
INSERT INTO EMPLOYEE (EMPID,EMPNAME,EMPSALARY) VALUES (1,'SAI',100)

INSERT INTO EMPLOYEE (EMPID,EMPNAME,EMPSALARY) VALUES (2,'KUMAR',200)
INSERT INTO EMPLOYEE (EMPID,EMPNAME,EMPSALARY) VALUES (3,'SATYA',300)
INSERT INTO EMPLOYEE (EMPID,EMPNAME,EMPSALARY) VALUES (4,'SRINU',400)

INSERT INTO EMPLOYEE (EMPID,EMPNAME) VALUES (5,'MANI')
INSERT INTO EMPLOYEE (EMPID,EMPNAME) VALUES (6,'RAHUL')

/* READ , RETRIVE AND SHOW THE DATA */

/* *-> SELECTING ALL THE COLUMNS IN THE TABLE AND SHOWING THE DATA*/
SELECT *FROM EMPLOYEE

/* USING DQL -> CAN WE SHOW SPECIFIC COLUMNS */

SELECT EMPID,EMPNAME FROM EMPLOYEE

/* USING DQL CAN WE SELECT A SPECIFIC ROW TO SHOW THE DATA -> YES -> USING WHERE CONDITION*/

SELECT *FROM EMPLOYEE WHERE EMPNAME='SATYA'

SELECT EMPSALARY FROM EMPLOYEE WHERE EMPNAME='SAI'

/* SHOW THE ROWS WHICH ARE HAVING NULL VALUES */

SELECT *FROM EMPLOYEE WHERE EMPSALARY IS NULL

UPDATE EMPLOYEE SET EMPNAME='MANIKANTA' WHERE EMPNAME='MANI'

UPDATE EMPLOYEE SET EMPNAME='KLRAHUL' WHERE EMPSALARY IS NULL

UPDATE EMPLOYEE SET EMPNAME='MANIKANTA' WHERE EMPID=5

UPDATE EMPLOYEE SET EMPSALARY=500 WHERE EMPID=5

UPDATE EMPLOYEE SET EMPSALARY=600 WHERE EMPID=6